[allowlist]
description = "Allow known false positives and generated output"
paths = [
  '''^\.mastra/output/.*''',
  '''^docs/.*'''
]
regexes = [
  '''OPENROUTER_API_KEY''',
  '''NEXT_PUBLIC_SUPABASE_ANON_KEY''',
  '''SUPABASE_SERVICE_ROLE_KEY''',
  '''GOOGLE_API_KEY'''
]

title = "IFS Gitleaks Config"

[allowlist]
paths = [
  "node_modules/",
  ".next/",
  ".mastra/output/",
  ".obsidian/",
  "coverage/",
  "supabase/.temp/"
]

# Optional: allowlist env VAR NAMES that are public by design (not values)
# Uncomment if you see false positives on these names
# regexes = [
#   '''NEXT_PUBLIC_[A-Z0-9_]+'''
# ]
