# litellm.config.yaml
model_list:
  - model_name: z-ai/glm-4.5-air
    litellm_params:
      model: openrouter/z-ai/glm-4.5-air
      api_base: https://openrouter.ai/api/v1
      api_key: os.environ/OPENROUTER_API_KEY
      extra_headers:
        HTTP-Referer: http://localhost:4000
        X-Title: LiteLLM Local

litellm_settings:
  set_verbose: True

guardrail_settings:
  prompt_injection:
    callbacks:
      - "lakera_prompt_injection"
    default_on: True
