import { OnboardingQuestion } from './types';

export const QUESTION_BANK: OnboardingQuestion[] = [
  // Stage 1
  {
    id: 'S1_Q1',
    stage: 1,
    type: 'single_choice',
    prompt: 'You\'re about to share important work publicly. What happens inside you?',
    helper: 'There\'s no right answer—just notice what feels most true.',
    options: [
      { value: 'surge_energy', label: 'A surge of energy—this is where I come alive' },
      { value: 'methodical_checking', label: 'Methodical checking of every detail' },
      { value: 'wondering_reception', label: 'Wondering how it will land with people' },
      { value: 'noticing_improvement', label: 'Noticing what could still be better' },
    ],
    order_hint: 1,
    active: true,
    created_at: '',
  },
  {
    id: 'S1_Q2',
    stage: 1,
    type: 'single_choice',
    prompt: 'Plans suddenly changed. Your immediate response?',
    helper: 'Trust your first instinct.',
    options: [
      { value: 'energized_possibilities', label: 'Feel energized by the new possibilities' },
      { value: 'protect_secure', label: 'Quickly identify what needs protecting or secured' },
      { value: 'check_affected', label: 'Check who might be affected by the change' },
      { value: 'analyze_wrong', label: 'Analyze what went wrong with the original plan' },
    ],
    order_hint: 2,
    active: true,
    created_at: '',
  },
  {
    id: 'S1_Q3',
    stage: 1,
    type: 'single_choice',
    prompt: 'Someone seems upset with you but hasn\'t said why. You:',
    helper: 'Notice what your system wants to do first.',
    options: [
      { value: 'give_space', label: 'Give them space to process their feelings on their own' },
      { value: 'directly_ask', label: 'Directly ask them what\'s happening for them' },
      { value: 'review_actions', label: 'Review what you might have done to cause it' },
      { value: 'focus_elsewhere', label: 'Focus on something else entirely to get your mind off it' },
    ],
    order_hint: 3,
    active: true,
    created_at: '',
  },
  {
    id: 'S1_Q4',
    stage: 1,
    type: 'single_choice',
    prompt: 'You\'ve finished something significant. Your first thought is?',
    helper: 'What comes up immediately?',
    options: [
      { value: 'whats_next', label: 'Already thinking about what\'s next on the list' },
      { value: 'ensure_perfect', label: 'Ensuring nothing was missed and all details are perfect' },
      { value: 'who_share', label: 'Who can I share this with?' },
      { value: 'could_be_better', label: 'What could have been done better?' },
    ],
    order_hint: 4,
    active: true,
    created_at: '',
  },
  {
    id: 'S1_Q5',
    stage: 1,
    type: 'single_choice',
    prompt: 'A wave of sadness appears, seemingly from nowhere. Your instinct is to:',
    helper: 'What\'s your automatic response?',
    options: [
      { value: 'push_down_busy', label: 'Push it down and get busy with a task or distraction' },
      { value: 'analyze_logical', label: 'Try to analyze it and figure out the logical reason you\'re feeling this way' },
      { value: 'let_feel', label: 'Let yourself feel it, maybe getting quiet or listening to music that matches the mood' },
      { value: 'judge_emotional', label: 'Judge yourself for being "too emotional" or "negative"' },
    ],
    order_hint: 5,
    active: true,
    created_at: '',
  },
  // Stage 2
  {
    id: 'S2_Q1',
    stage: 2,
    type: 'single_choice',
    prompt: 'When you push yourself hard, it\'s usually because:',
    helper: 'What drives the intensity?',
    options: [
      { value: 'love_challenge', label: 'I genuinely love the challenge and the feeling of growth' },
      { value: 'prove_worth', label: 'I feel a need to prove my worth to myself or others' },
      { value: 'others_counting', label: 'I believe that others are counting on me to deliver' },
      { value: 'intolerance_mediocrity', label: 'I have a deep intolerance for mediocrity or falling short' },
    ],
    order_hint: 1,
    theme_weights: { achievement: 0.8, perfectionism: 0.4, self_criticism: 0.3 },
    active: true,
    created_at: '',
  },
  {
    id: 'S2_Q2',
    stage: 2,
    type: 'single_choice',
    prompt: 'That inner voice that tells you "it\'s not good enough yet" is trying to:',
    helper: 'What\'s its intention?',
    options: [
      { value: 'protect_judgment', label: 'Protect you from being judged or rejected by others' },
      { value: 'prevent_complacency', label: 'Keep you from getting complacent or lazy' },
      { value: 'fullest_potential', label: 'Make sure you live up to your absolute fullest potential' },
      { value: 'prevent_catastrophe', label: 'Prevent a catastrophic mistake or failure from happening' },
    ],
    order_hint: 2,
    theme_weights: { perfectionism: 0.9, self_criticism: 0.7, safety: 0.4 },
    active: true,
    created_at: '',
  },
  {
    id: 'S2_Q3',
    stage: 2,
    type: 'single_choice',
    prompt: 'When you focus on the needs of others, it\'s often driven by a desire to:',
    helper: 'What\'s underneath the focus on others?',
    options: [
      { value: 'genuine_harmony', label: 'Create genuine harmony and connection in the group' },
      { value: 'everyone_included', label: 'Make sure everyone feels seen and included' },
      { value: 'avoid_conflict', label: 'Avoid conflict or disapproval at all costs' },
      { value: 'feel_needed', label: 'Feel needed and valuable to the people around you' },
    ],
    order_hint: 3,
    theme_weights: { relational: 0.8, conflict_avoidance: 0.6, caretaking: 0.5 },
    active: true,
    created_at: '',
  },
  {
    id: 'S2_Q4',
    stage: 2,
    type: 'single_choice',
    prompt: 'When you\'re planning for risks, you\'re primarily:',
    helper: 'What are you protecting?',
    options: [
      { value: 'protect_pain', label: 'Protecting yourself from future pain or disappointment' },
      { value: 'protect_others', label: 'Ensuring that your actions don\'t negatively affect others' },
      { value: 'maintain_control', label: 'Maintaining a sense of order and control over the situation' },
      { value: 'prevent_embarrassment', label: 'Preventing the possibility of failure or embarrassment' },
    ],
    order_hint: 4,
    theme_weights: { safety: 0.9, control: 0.7, anxiety: 0.4 },
    active: true,
    created_at: '',
  },
  {
    id: 'S2_Q5',
    stage: 2,
    type: 'single_choice',
    prompt: 'The \'part\' of you that distracts you or makes you procrastinate is often trying to:',
    helper: 'What\'s it protecting you from?',
    options: [
      { value: 'needed_break', label: 'Give you a much-needed break from constant pressure' },
      { value: 'avoid_threatening', label: 'Keep you away from a feeling that seems threatening or overwhelming' },
      { value: 'rebel_expectations', label: 'Rebel against the rules or expectations being placed on you' },
      { value: 'conserve_energy', label: 'Conserve energy because the task ahead feels too big to face' },
    ],
    order_hint: 5,
    theme_weights: { avoidance: 0.9, overwhelm: 0.6, restlessness: 0.3 },
    active: true,
    created_at: '',
  },
  {
    id: 'S2_Q6',
    stage: 2,
    type: 'single_choice',
    prompt: 'When someone offers you genuine, unconditional support, your first internal reaction is often:',
    helper: 'What comes up automatically?',
    options: [
      { value: 'relief', label: 'Relief. Finally, I can let my guard down' },
      { value: 'suspicion', label: 'Suspicion. What do they really want from me?' },
      { value: 'discomfort_burden', label: 'Discomfort. I don\'t want to be a burden to them' },
      { value: 'urge_repay', label: 'Gratitude, but with an immediate urge to "repay" the kindness' },
    ],
    order_hint: 6,
    theme_weights: { independence: 0.7, safety: 0.5, relational: 0.4 },
    active: true,
    created_at: '',
  },
  {
    id: 'S2_Q7',
    stage: 2,
    type: 'single_choice',
    prompt: 'When emotions feel too big or overwhelming, the part that steps in usually tries to:',
    helper: 'How do you handle intensity?',
    options: [
      { value: 'analyze_rationalize', label: 'Analyze and rationalize the feelings away' },
      { value: 'numb_shutdown', label: 'Numb or shut down the emotional experience entirely' },
      { value: 'express_anger', label: 'Express the intensity through anger or frustration' },
      { value: 'seek_comfort', label: 'Seek comfort or soothing from others or substances' },
    ],
    order_hint: 7,
    theme_weights: { overwhelm: 0.8, criticism: 0.4, avoidance: 0.5 },
    active: true,
    created_at: '',
  },
  {
    id: 'S2_Q8',
    stage: 2,
    type: 'single_choice',
    prompt: 'Your tendency to \'do everything yourself\' often comes from:',
    helper: 'What drives the self-reliance?',
    options: [
      { value: 'dont_trust_others', label: 'Not trusting others to do things correctly or completely' },
      { value: 'avoid_vulnerability', label: 'Wanting to avoid owing anyone anything or being vulnerable' },
      { value: 'only_understand', label: 'Believing you\'re the only one who truly understands what needs to be done' },
      { value: 'fear_weakness', label: 'Fear that asking for help reveals weakness or inadequacy' },
    ],
    order_hint: 8,
    theme_weights: { independence: 0.9, perfectionism: 0.5, safety: 0.4 },
    active: true,
    created_at: '',
  },
  {
    id: 'S2_Q9',
    stage: 2,
    type: 'single_choice',
    prompt: 'When you notice yourself being self-critical, that voice is usually:',
    helper: 'What\'s the critic trying to do?',
    options: [
      { value: 'motivate_better', label: 'Trying to motivate you to do better next time' },
      { value: 'protect_judgment', label: 'Protecting you from others\' judgment by getting there first' },
      { value: 'express_disappointment', label: 'Expressing disappointment that you didn\'t live up to your standards' },
      { value: 'punish_failure', label: 'Punishing you for a perceived failure or mistake' },
    ],
    order_hint: 9,
    theme_weights: { self_criticism: 0.9, perfectionism: 0.6, shame: 0.4 },
    active: true,
    created_at: '',
  },
  {
    id: 'S2_Q10',
    stage: 2,
    type: 'single_choice',
    prompt: 'When you feel compelled to fix someone else\'s problem, you\'re often driven by:',
    helper: 'What motivates the rescuing?',
    options: [
      { value: 'genuine_empathy', label: 'Genuine empathy and desire to reduce their suffering' },
      { value: 'discomfort_pain', label: 'Discomfort with witnessing someone else\'s pain' },
      { value: 'responsible_wellbeing', label: 'A sense that you\'re responsible for others\' wellbeing' },
      { value: 'feel_useful', label: 'Wanting to feel useful and needed by others' },
    ],
    order_hint: 10,
    theme_weights: { caretaking: 0.8, relational: 0.6, control: 0.3 },
    active: true,
    created_at: '',
  },
  {
    id: 'S2_Q11',
    stage: 2,
    type: 'single_choice',
    prompt: 'The part of you that always needs to be productive or busy is trying to:',
    helper: 'What drives the constant doing?',
    options: [
      { value: 'prove_worth', label: 'Prove your worth through constant achievement' },
      { value: 'avoid_feelings', label: 'Avoid uncomfortable feelings that arise in stillness' },
      { value: 'stay_ahead', label: 'Stay ahead of potential problems or responsibilities' },
      { value: 'feel_control', label: 'Feel in control of your time and circumstances' },
    ],
    order_hint: 11,
    theme_weights: { restlessness: 0.8, achievement: 0.4, avoidance: 0.5 },
    active: true,
    created_at: '',
  },
  {
    id: 'S2_Q12',
    stage: 2,
    type: 'single_choice',
    prompt: 'When tension arises in relationships, your instinct to smooth things over usually aims to:',
    helper: 'What are you protecting by peacekeeping?',
    options: [
      { value: 'preserve_connection', label: 'Preserve the connection and prevent abandonment' },
      { value: 'maintain_image', label: 'Maintain your image as the "good" or "easy" person' },
      { value: 'avoid_discomfort', label: 'Avoid the discomfort of witnessing others\' distress' },
      { value: 'keep_safe', label: 'Keep everyone safe from potentially hurtful emotions' },
    ],
    order_hint: 12,
    theme_weights: { conflict_avoidance: 0.9, relational: 0.6, safety: 0.4 },
    active: true,
    created_at: '',
  },
  // Stage 3
  {
    id: 'S3_Q1',
    stage: 3,
    type: 'multi_select',
    prompt: 'Where do you typically feel stress or tension in your body?',
    helper: 'Select all that apply—bodies hold information.',
    options: [
      { value: 'chest', label: 'Chest (tightness, pressure)' },
      { value: 'shoulders_neck', label: 'Shoulders/Neck (tension, knots)' },
      { value: 'stomach', label: 'Stomach (churning, knots, acidity)' },
      { value: 'head', label: 'Head (pressure, fog, headache)' },
      { value: 'nowhere', label: 'Nowhere specific / I don\'t notice it in my body' },
    ],
    order_hint: 1,
    active: true,
    created_at: '',
  },
  {
    id: 'S3_Q2',
    stage: 3,
    type: 'free_text',
    prompt: 'Complete this sentence: "I absolutely must..."',
    helper: 'What feels non-negotiable to you? A few words are enough.',
    options: [],
    order_hint: 2,
    active: true,
    created_at: '',
  },
  {
    id: 'S3_Q3',
    stage: 3,
    type: 'free_text',
    prompt: 'What is your first thought when you realize you\'ve made a mistake?',
    helper: 'The very first thing that goes through your mind.',
    options: [],
    order_hint: 3,
    active: true,
    created_at: '',
  },
  {
    id: 'S3_Q4',
    stage: 3,
    type: 'single_choice',
    prompt: 'Which feeling do you trust the least?',
    helper: 'Which one feels most unreliable or dangerous?',
    options: [
      { value: 'anger', label: 'Anger' },
      { value: 'sadness', label: 'Sadness' },
      { value: 'joy', label: 'Joy' },
      { value: 'fear', label: 'Fear' },
      { value: 'contentment', label: 'Contentment' },
    ],
    order_hint: 4,
    active: true,
    created_at: '',
  },
];
