name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  secrets-scan:
    name: Secrets Scan (temporarily disabled)
    runs-on: ubuntu-latest
    steps:
      - name: CI temporarily disabled for secrets scan
        run: echo "ci temporarily disabled"

  build:
    name: Typecheck, Lint, Build (temporarily disabled)
    runs-on: ubuntu-latest
    needs: secrets-scan
    steps:
      - name: CI temporarily disabled for build
        run: echo "ci temporarily disabled"

