name: Auto-enable PR auto-merge
on:
  pull_request:
    types: [opened, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable:
    if: >
      github.event.pull_request.draft == false &&
      (github.actor == 'brandongalang' ||
       contains(join(github.event.pull_request.labels.*.name, ','), 'automerge'))
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: SQUASH
