name: Memory Update Cron

on:
  schedule:
    # Daily at 08:00 UTC; adjust as needed
    - cron: '0 8 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  call-cron-endpoint:
    if: ${{ secrets.APP_BASE_URL != '' && secrets.CRON_SECRET != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/cron/memory-update
        env:
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          if [ -z "$APP_BASE_URL" ] || [ -z "$CRON_SECRET" ]; then
            echo "APP_BASE_URL or CRON_SECRET not configured in repo secrets" >&2
            exit 1
          fi
          set -euo pipefail
          CODE=$(curl -s -o response.json -w "%{http_code}" -X POST \
            "$APP_BASE_URL/api/cron/memory-update" \
            -H "Authorization: Bearer $CRON_SECRET")
          echo "HTTP $CODE"
          cat response.json
          if [ "$CODE" -lt 200 ] || [ "$CODE" -ge 300 ]; then
            exit 1
          fi
